---
title: "Two Parameters"
author: "Aditya Narayan"
format: html
execute:
  echo: FALSE
---
```{r}
#| message: FALSE
library(tidyverse)
library(primer.data)
library(tidybayes)
library(brms)
library(gtsummary)
```

```{r}
#| cache: TRUE
fit_male_height <- brm(formula = height ~ 1, data = nhanes, family = gaussian(), silent = 2, refresh = 0,
seed = 12)
```

```{r}
nhanes |>
  filter(sex == "Male", age > 18) |>
    select(height) |>
      drop_na() |>
        ggplot(aes(x = height)) +
          geom_histogram(bins = 50) +
            labs(title = "Male Adult Height in the US in 2010",
            x = "Height (cm)",
            y = "Count",
            caption = "Source: National Health and Nutrition Examanation Survey")
```

```{r}
#| label: plot
ndata <- tibble(.rows = 1)
fit_male_height |>
  add_predicted_draws(newdata = ndata) |>
    ggplot(aes(x = .prediction)) +
    geom_histogram(aes(y = after_stat(count/sum(count))), bins = 100) +
    labs(title = "Posterior for height of random male",
    subtitle = "Uncertainty for a single male is much greater than expected",
    x = "Height (cm)",
    y = "Probability",
    caption = "Data source: NHANES") +
    scale_x_continuous(labels = scales::number_format()) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1))
```

```{r}
"Using the NHANES dataset from the National Health and Nutrition Examination Survey, which includes 15 variables such as height and weight from 2009 to 2011, we aim to create a model of height for adult men to address specific questions about height probabilities and related statistical aspects. Since the data is over a decade old it is misleading of the current population. We modeled a simple linear regression model with the formula being height ~1 and the dependent variable is the height. After analysis, it shows a 28.3% chance of this happening."
```

```{r}
fit_male_height |>
  add_predicted_draws(newdata = ndata) |>
    mutate(tall = if_else(.prediction > 180, TRUE, FALSE)) |>
    summarize(odds = mean(tall))
```

```{r}
tbl_regression(fit_male_height, intercept = TRUE)
```





